pushgateway-enabled = true
# prometheus-scrape-interval = "5m"

[[endpoint]]
job-name = "main_app"
url = "http://localhost:3030"
# scrape-interval = "5s"

[[endpoint]]
job-name = "secondary_app"
url = "http://localhost:3030"
