on:
  release:
    types:
      - published

jobs:
  validate-version:
    name: validate `Cargo.toml` version matches tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.validate.outputs.VERSION }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: validate version
        id: validate
        run: |
          # Extract the version from the Cargo.toml
          VERSION=$(cat "Cargo.toml" | grep '^version' | awk '{ split($0,version,"=") ; gsub(/[\ \"]/, "", version[2]) ; print version[2] }')
          echo $VERSION >> "$GITHUB_OUTPUT"
          if [ "v${VERSION}" != "${{ github.event.release.tag_name }}" ]; then
            echo "::error file=Cargo.toml::Version set in Cargo.toml (v${VERSION}) does not match release version (${{ github.event.release.tag_name }})"
            exit 1
          fi

  attach-artifacts:
    name: (${{ matrix.platform.name }}) build and attach artifacts to release
    permissions:
      contents: write
    needs: validate-version
    strategy:
      matrix:
        platform:
          - name: linux_x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: am
            file-name: am-linux-x86_64
          - name: linux_aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: am
            file-name: am-linux-aarch64
          - name: macos_x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: am
            file-name: am-macos-x86_64
          - name: macos_aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: am
            file-name: am-macos-aarch64

    runs-on: ${{ matrix.platform.os }}
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: prepare binary
        run: |
          mkdir -p /tmp/artifact/
          cp "target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}" "/tmp/artifact/${{ matrix.platform.file-name }}"

      - name: calculate sha256sum
        run: sha256sum /tmp/artifact/${{ matrix.platform.file-name }} >> /tmp/artifact/${{ matrix.platform.file-name }}.sha256

      - name: upload SHA256 for next step
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.file-name }}.sha256
          path: /tmp/artifact/${{ matrix.platform.file-name }}.sha256

      - name: attach artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifact/${{ matrix.platform.file-name }}
            /tmp/artifact/${{ matrix.platform.file-name }}.sha256

  homebrew-release:
    runs-on: ubuntu-latest
    name: Update Homebrew tap formula
    needs: [attach-artifacts, validate-version]

    steps:
      - name: prepare folder
        run: mkdir -p /tmp/artifact

      - name: get the SHA256 artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifact

      - name: trigger homebrew workflow
        working-directory: /tmp/artifact/
        env:
          AM_VERSION: ${{ needs.validate-version.outputs.version }}
        run: |
          gh workflow run update_formula.yml \
          -R autometrics-dev/homebrew-tap \
          -f AM_VERSION=$AM_VERSION \
          -f SHA256_AARCH64_APPLE_DARWIN=$(cat am-macos-aarch64.sha256 | awk '{print $1}') \
          -f SHA256_X86_64_APPLE_DARWIN=$(cat am-macos-x86_64.sha256 | awk '{print $1}') \
          -f SHA256_AARCH64_LINUX_GNU=$(cat am-linux-aarch64.sha256 | awk '{print $1}') \
          -f SHA256_X86_64_LINUX_GNU=$(cat linux_x86_64.sha256.sha256 | awk '{print $1}')
