# This workflow will be triggered by a GitHub pull-request and pushes to main.
# It will verify that the code compiles, that the tests pass and that
# clippy does not complain (too much) and finally that the code is formatted
# according to cargo fmt. If it was a push to main, then it will also trigger a
# build, and a deploy to dev.
---
name: Test

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          cache: true

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      # - name: Lint code
      #   uses: actions-rs/clippy-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     args: --all-features

      - name: Run tests
        run: cargo test
